/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import penjualan.Koneksi;
import javax.swing.*; 
import java.awt.*; 
import java.sql.*; 
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import Controllers.PenjualanController;
import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author smkiutama1
 */
public class Form_penjualan extends javax.swing.JFrame {
    private DefaultTableModel model;
    String tanggal;
   
    public void totalBiaya(){
        int jumlahbaris = tblpenjualan.getRowCount();
        int totalbiaya = 0;
        int jumlahbarang, hargabarang;
        for (int i = 0; i <jumlahbaris; i++){
            jumlahbarang = Integer.parseInt(tblpenjualan.getValueAt(i, 3).toString());
            hargabarang = Integer.parseInt(tblpenjualan.getValueAt(i, 4).toString());
            totalbiaya = totalbiaya + (jumlahbarang + hargabarang);
        }
        txttotal.setText(String.valueOf(totalbiaya));
        txtjumlah.setText("Rp "+ totalbiaya +"00");
        
    }
    
    private void autonumber(){
         try{
	Connection koneksi = Koneksi.getKoneksi();
	Statement stt = koneksi.createStatement();
	String SQL = "SELECT * FROM tblpenjualan where nofaktur='"+txtfaktur.getText().toString()+"'";
	ResultSet res = stt.executeQuery(SQL);
	res.absolute(1);
//	TampilGridDetail;  bisa juga pake loaddata
	txttanggal.setText(res.getString("tglpenjualan"));
	cmbpetugas.setSelectedItem(res.getString("idpetugas"));
	txtbayar.setText(res.getString("bayar"));
	txtsisa.setText(res.getString("sisa"));
	txttotal.setText(res.getString("total"));
	btnsave.setEnabled(false);
	txtfaktur.setEnabled(false);
	btncari.setEnabled(false);
} catch (SQLException ex) {
	System.out.println("Terjadi Error"+ex.getMessage());	
    }
                                        
    }
    /**
     * Creates new form Form_penjualan
     */
    public Form_penjualan() {
            initComponents();
            TampilBarang();
            TampilPetugas();
            loadData();
            tanggalotomatis();
            Connection conn = Koneksi.getKoneksi();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtfaktur = new javax.swing.JTextField();
        cmbpetugas = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtpetugas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txttanggal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbkodebarang = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        txthrgjual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtnmbarang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpenjualan = new javax.swing.JTable();
        btnaddnew = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtbayar = new javax.swing.JTextField();
        txtsisa = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        btncari = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entri Data Penjualan Barang");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(245, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(219, 219, 219))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 730, 70));

        jLabel2.setText("No.Faktur");

        jLabel3.setText("ID Petguas");

        cmbpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbpetugasActionPerformed(evt);
            }
        });

        jLabel4.setText("Nama Petugas");

        txtpetugas.setEnabled(false);
        txtpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtpetugasActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal Penjualan");

        txttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalActionPerformed(evt);
            }
        });

        jLabel6.setText("Data Barang");

        jLabel7.setText("Kode Barang");

        cmbkodebarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbkodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbkodebarangActionPerformed(evt);
            }
        });

        jLabel8.setText("Nama Barang");

        txthrgjual.setEnabled(false);
        txthrgjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txthrgjualActionPerformed(evt);
            }
        });

        jLabel9.setText("Harga Jual");

        txtnmbarang.setEnabled(false);
        txtnmbarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnmbarangActionPerformed(evt);
            }
        });

        jLabel10.setText("Stok");

        txtstok.setEnabled(false);
        txtstok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtstokActionPerformed(evt);
            }
        });

        jLabel11.setText("Jumlah");

        btnhitung.setText("Hitung");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });

        jLabel12.setText("Sub Total Rp");

        txtsubtotal.setEnabled(false);
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });

        btnadd.setText("Add Item");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Grid Data Barang"));

        tblpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpenjualanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblpenjualan);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        btnaddnew.setText("Add New");
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });

        btnsave.setText("Save Transaction");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        jLabel13.setText("Bayar Rp");

        jLabel14.setText("Sisa Rp");

        jLabel15.setText("Total Rp");

        txtbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbayarActionPerformed(evt);
            }
        });

        txtsisa.setEnabled(false);

        txttotal.setEnabled(false);

        btncari.setText("Cari Data");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btncari)
                                        .addGap(82, 82, 82)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txttanggal))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cmbpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel4))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(cmbkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtpetugas)
                                            .addComponent(txtnmbarang, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                                            .addComponent(txthrgjual, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnhitung)
                                                .addGap(21, 21, 21)
                                                .addComponent(jLabel12)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtsubtotal))))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(btnaddnew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btncancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnclose)
                        .addGap(78, 78, 78)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtsisa, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addComponent(txttotal)
                            .addComponent(txtbayar))))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtfaktur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txttanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncari))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbkodebarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtnmbarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txthrgjual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtjumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnhitung)
                    .addComponent(jLabel12)
                    .addComponent(txtsubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnadd)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddnew)
                    .addComponent(btnsave)
                    .addComponent(btncancel)
                    .addComponent(btnclose)
                    .addComponent(jLabel13)
                    .addComponent(txtbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtsisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txttotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 730, 640));

        pack();
    }// </editor-fold>                        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfaktur = new javax.swing.JTextField();
        cmbpetugas = new javax.swing.JComboBox<>();
        txtpetugas = new javax.swing.JTextField();
        txttanggal = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cmbkodebarang = new javax.swing.JComboBox<>();
        txtnmbarang = new javax.swing.JTextField();
        txthrgjual = new javax.swing.JTextField();
        txtstok = new javax.swing.JTextField();
        txtjumlah = new javax.swing.JTextField();
        btnhitung = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtsubtotal = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblpenjualan = new javax.swing.JTable();
        txtbayar = new javax.swing.JTextField();
        txtsisa = new javax.swing.JTextField();
        txttotal = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnsave = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Penjualan");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, -1, -1));

        jLabel2.setText("NoFaktur");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 50, -1, -1));

        jLabel3.setText("ID Petugas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel4.setText("NamaPetugas");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, -1, -1));

        jLabel5.setText("Tanggal Penjualan");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 50, -1, -1));

        txtfaktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfakturActionPerformed(evt);
            }
        });
        jPanel1.add(txtfaktur, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 90, -1));

        cmbpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH", " " }));
        cmbpetugas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbpetugasItemStateChanged(evt);
            }
        });
        jPanel1.add(cmbpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 90, -1));

        txtpetugas.setEnabled(false);
        jPanel1.add(txtpetugas, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 90, 150, -1));

        txttanggal.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/MMM/yyyy"))));
        txttanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttanggalActionPerformed(evt);
            }
        });
        jPanel1.add(txttanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 120, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("DataPenjualan"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Kode Barang");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 24, -1, -1));

        jLabel7.setText("Nama Barang");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, -1, -1));

        jLabel8.setText("Harga Jual ");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, -1));

        jLabel9.setText("Stok");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        jLabel10.setText("Jumlah");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));

        cmbkodebarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH" }));
        cmbkodebarang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbkodebarangItemStateChanged(evt);
            }
        });
        jPanel2.add(cmbkodebarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, -1));

        txtnmbarang.setEnabled(false);
        jPanel2.add(txtnmbarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 110, -1));

        txthrgjual.setEnabled(false);
        jPanel2.add(txthrgjual, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, 110, -1));

        txtstok.setEnabled(false);
        jPanel2.add(txtstok, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 110, -1));
        jPanel2.add(txtjumlah, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 120, 70, -1));

        btnhitung.setText("HITUNG");
        btnhitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhitungActionPerformed(evt);
            }
        });
        jPanel2.add(btnhitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, -1, -1));

        jLabel11.setText("SUB TOTAL");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 120, -1, -1));

        txtsubtotal.setText("0");
        txtsubtotal.setEnabled(false);
        txtsubtotal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtsubtotalCaretUpdate(evt);
            }
        });
        txtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsubtotalActionPerformed(evt);
            }
        });
        jPanel2.add(txtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 70, -1));

        btnadd.setText("AddI tem");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });
        jPanel2.add(btnadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, -1, -1));

        tblpenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11", "Title 12", "Title 13"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblpenjualan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblpenjualanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblpenjualanMouseEntered(evt);
            }
        });
        tblpenjualan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tblpenjualanInputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(tblpenjualan);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 660, 150));

        txtbayar.setText("0");
        txtbayar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtbayarCaretUpdate(evt);
            }
        });
        jPanel2.add(txtbayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 410, 140, -1));
        jPanel2.add(txtsisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 140, -1));

        txttotal.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txttotalCaretUpdate(evt);
            }
        });
        txttotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttotalActionPerformed(evt);
            }
        });
        jPanel2.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 470, 140, -1));

        jLabel12.setText("Bayar Rp");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 410, -1, -1));

        jLabel13.setText("Sisa Rp");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 440, -1, -1));

        jLabel14.setText("Total Rp");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 50, -1));

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        jPanel2.add(btnclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, -1, -1));

        btnsave.setText("AddNew");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        btnsave.setText("Save Transaksi");
        btnsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsaveActionPerformed(evt);
            }
        });
        jPanel2.add(btnsave, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, -1, -1));

        btncancel.setText("Hapus");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });
        jPanel2.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, -1, -1));

        btncancel.setText("Clear");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(btncancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 690, 500));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 729, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
      
    private void loadData(){
        model = new DefaultTableModel();
        model = new DefaultTableModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();

        model.addColumn("NoFaktur");
        model.addColumn("KodeBarang");
        model.addColumn("NamaBarang");
        model.addColumn("HargaJual");
        model.addColumn("Stok");
        model.addColumn("Jumlah");
        model.addColumn("SubTotal");
        model.addColumn("IDPetugas");
        model.addColumn("TanggalPenjualan");
        model.addColumn("NamaPetugas");
        model.addColumn("Bayar");
        model.addColumn("Sisa");
        model.addColumn("Total");
        
        try {
            String sql = "SELECT A.NoFaktur, A.TglPenjualan, A.IDPetugas, A.Bayar, A.Sisa, A.Total, B.NoFaktur, B.KodeBarang, B.Jumlah, B.SubTotal, C.KodeBarang, C.NamaBarang, C.HargaJual, C.Stok, D.NamaPetugas "
                    + "FROM tbldetailpenjualan B "
                    + "LEFT JOIN tblpenjualan A ON B.NoFaktur = A.NoFaktur "
                    + "LEFT JOIN tblbarang C ON B.KodeBarang = C.KodeBarang "
                    + "LEFT JOIN tblpetugas D ON A.IDPetugas = D.IDPetugas";
            
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);
            while (r.next()) {
                model.addRow(new Object[]{
                    r.getString("NoFaktur"),
                    r.getString("KodeBarang"),
                    r.getString("NamaBarang"),
                    r.getString("HargaJual"),
                    r.getString("Stok"),
                    r.getString("Jumlah"),
                    r.getString("SubTotal"),
                    r.getString("IDPetugas"),
                    r.getDate("TglPenjualan"),
                    r.getString("NamaPetugas"),
                    r.getString("Bayar"),
                    r.getString("Sisa"),
                    r.getString("Total")
                });
            }
            
            tblpenjualan.setModel(model);
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Terjadi Error");
        }   
}
    
    private void TampilBarang() {
        try {
            String sql = "SELECT * FROM tblbarang";
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {

                cmbkodebarang.addItem(r.getString("KodeBarang"));
            }
        } catch (SQLException e) {
        }
    }
    
    private void TampilPetugas() {
        try {
            String sql = "SELECT * FROM tblpetugas";
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            while (r.next()) {

                cmbpetugas.addItem(r.getString("IDPetugas"));
            }
        } catch (SQLException e) {

        }
    }
    
    private void getData() {

        String NM = txtfaktur.getText();
        String KB = cmbkodebarang.getSelectedItem().toString();
        String JM = txtjumlah.getText();

        if ((NM.isEmpty()) | (KB.isEmpty()) | (JM.isEmpty())) {
            JOptionPane.showMessageDialog(null, "data tidak boleh kosong, silahkan dilengkapi");
            cmbkodebarang.requestFocus();
        } else {
            try {
                Connection c = Koneksi.getKoneksi();
                Statement stt = c.createStatement();
                String SQL = "insert into tbldetailpenjualan values('" + txtfaktur.getText() + "',"
                        + "'" + cmbkodebarang.getSelectedItem() + "',"
                        + "'" + txtjumlah.getText() + "',"
                        + "'" + txtsubtotal.getText() + "')";
                stt.executeUpdate(SQL);

                Connection kon1 = Koneksi.getKoneksi();
                Statement stt1 = kon1.createStatement();
                String SQL1 = "Update tblbarang Set stok=stok - '" + txtjumlah.getText() + "'"
                        + "Where kodebarang='" + cmbkodebarang.getSelectedItem().toString() + "'";
                stt1.executeUpdate(SQL1);
                String[] data = new String[7];
                data[0] = txtfaktur.getText();
                data[1] = cmbkodebarang.getSelectedItem().toString();
                data[2] = txtnmbarang.getText();
                data[3] = txthrgjual.getText();
                data[4] = txtstok.getText();
                data[5] = txtjumlah.getText();
                data[6] = txtsubtotal.getText();
                model.insertRow(0, data);

                cmbkodebarang.requestFocus();
                btnadd.setEnabled(false);
                btnsave.setEnabled(true);
                cmbkodebarang.requestFocus();
            } catch (Exception ex) {
                System.out.println("Terjadi Error" + ex.getMessage());
            } finally {
                kosong();
            }
        }
    }
    
    private void kosong() {
        cmbpetugas.setSelectedIndex(0);
        txtbayar.setText("");
        txtsisa.setText("");
        txttotal.setText("");
        cmbkodebarang.setSelectedIndex(0);
        txtnmbarang.setText("");
        txthrgjual.setText("");
        txtstok.setText("");
        txtjumlah.setText("");
    }

    private void clear() {
        txtfaktur.setText("");
        txttanggal.setText("");
        cmbpetugas.setSelectedIndex(0);
        txtbayar.setText("");
        txtsisa.setText("");
        txttotal.setText("");
        cmbkodebarang.setSelectedIndex(0);
        txtnmbarang.setText("");
        txthrgjual.setText("");
        txtstok.setText("");
        txtjumlah.setText("");
        txtsubtotal.setText("");
    }

    private void tanggalotomatis() {
      Date tanggal = new Date();
      txttanggal.setText(""+ (String.format("%1$td/%1$tb/%1$tY",tanggal)));
  }
    public void tampilfaktur() {
  }
    
    private void cmbpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbpetugasActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tblpetugas WHERE IDPetugas='" + cmbpetugas.getSelectedItem().toString() + "'";
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String Nama = r.getString("NamaPetugas");
                if (Nama != null) {
                    txtpetugas.setText(Nama);
                } else {

                    txtpetugas.setText("Nilai kolom Jenis adalah null");
                }
            } else {

                txtpetugas.setText("");
            }
        } catch (SQLException e) {

            e.printStackTrace();
        }
    }//GEN-LAST:event_cmbpetugasActionPerformed

    private void txtpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtpetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtpetugasActionPerformed

    private void txthrgjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txthrgjualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthrgjualActionPerformed

    private void txtnmbarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnmbarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnmbarangActionPerformed

    private void txtstokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtstokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtstokActionPerformed

    private void btnhitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhitungActionPerformed
        // TODO add your handling code here:
        int a;
        int b;
        int c;
        a = Integer.parseInt(txthrgjual.getText());
        b = Integer.parseInt(txtjumlah.getText());
        c = a * b;
        txtsubtotal.setText(Integer.toString(c));
    }//GEN-LAST:event_btnhitungActionPerformed

    private void btnsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsaveActionPerformed
        // TODO add your handling code here:
//List<String[]> data = new ArrayList<>();
//        String noFaktur = null;
//        Date tglPenjualan=null;
//        String idPetugas=null;
//        String bayar=null;
//        String sisa=null;
//        String total=null;
//        penjualan.Store(data, noFaktur, tglPenjualan, idPetugas, bayar, sisa, total);
    }//GEN-LAST:event_btnsaveActionPerformed

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusActionPerformed
        int selectedRow = tblpenjualan.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih Data yang ingin di Hapus");
            return;
        }
        String kode = (String) model.getValueAt(selectedRow, 0);
        if (kode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int confirmDialog = JOptionPane.showConfirmDialog(this, "Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirmDialog == JOptionPane.YES_OPTION) {
                try {
                    Connection c = Koneksi.getKoneksi();
                    c.setAutoCommit(false);
                    String sqlDetailPenjualan = "DELETE FROM tbldetailpenjualan WHERE NoFaktur = ?";
                    PreparedStatement dDetailPenjualan = c.prepareStatement(sqlDetailPenjualan);
                    dDetailPenjualan.setString(1, kode);
                    dDetailPenjualan.executeUpdate();
                    String sqlPenjualan = "DELETE FROM tblpenjualan WHERE NoFaktur = ?";
                    PreparedStatement pPenjualan = c.prepareStatement(sqlPenjualan);
                    pPenjualan.setString(1, kode);
                    pPenjualan.executeUpdate();
                    c.commit();
                    JOptionPane.showMessageDialog(this, "Penghapusan Data Berhasil", "Success", JOptionPane.INFORMATION_MESSAGE);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Terjadi Kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                } finally {
                    loadData();
                    kosong();
                }
            }
        }

    }//GEN-LAST:event_btnhapusActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        clear();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void cmbkodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbkodebarangActionPerformed
        // TODO add your handling code here:
        try {
            String sql = "SELECT * FROM tblbarang WHERE KodeBarang='" + cmbkodebarang.getSelectedItem().toString() + "'";
            Connection c = Koneksi.getKoneksi();
            Statement s = c.createStatement();
            ResultSet r = s.executeQuery(sql);

            if (r.next()) {
                String Nama = r.getString("NamaBarang");
                String HargaJual = r.getString("HargaJual");
                String Stok = r.getString("Stok");
                if (Nama != null) {
                    txtnmbarang.setText(Nama);
                    txthrgjual.setText(HargaJual);
                    txtstok.setText(Stok);
                } else {

                    txtpetugas.setText("Nilai kolom Jenis adalah null");
                    txthrgjual.setText("Nilai kolom ini adalah null");
                    txtstok.setText("Nilai kolom ini adalah null");
                }
            } else {

                txtpetugas.setText("");
            }
        } catch (SQLException e) {

        }
    }//GEN-LAST:event_cmbkodebarangActionPerformed

    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnaddnewActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btncancelActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        getData();
    }//GEN-LAST:event_btnaddActionPerformed

    private void tblpenjualanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblpenjualanMouseClicked
        // TODO add your handling code here:
        int baris = tblpenjualan.getSelectedRow();
        if (baris == -1) {
            return;
        }

        if (tblpenjualan.getColumnCount() >= 13) {
            String kj = String.valueOf(tblpenjualan.getValueAt(baris, 0));
            txtfaktur.setText(kj);
            cmbkodebarang.setSelectedItem(tblpenjualan.getValueAt(baris, 1));
            String NamaBarang = String.valueOf(tblpenjualan.getValueAt(baris, 2));
            txtnmbarang.setText(NamaBarang);
            String HargaJual = String.valueOf(tblpenjualan.getValueAt(baris, 3));
            txthrgjual.setText(HargaJual);
            String Stok = String.valueOf(tblpenjualan.getValueAt(baris, 4));
            txtstok.setText(Stok);
            String jumlah = String.valueOf(tblpenjualan.getValueAt(baris, 5));
            txtjumlah.setText(jumlah);
            String SubTotal = String.valueOf(tblpenjualan.getValueAt(baris, 6));
            txtsubtotal.setText(SubTotal);
        }

        if (baris >= 0) {

            if (tblpenjualan.getValueAt(baris, 7) != null) {
                cmbpetugas.setSelectedItem(tblpenjualan.getValueAt(baris, 7));
            }

            java.util.Date TanggalPenjualan = (java.util.Date) tblpenjualan.getValueAt(baris, 8);
            txttanggal.setValue(TanggalPenjualan);
            String NamaPetugas = String.valueOf(tblpenjualan.getValueAt(baris, 9));
            txtpetugas.setText(NamaPetugas);
            String Bayar = String.valueOf(tblpenjualan.getValueAt(baris, 10));
            txtbayar.setText(Bayar);
            String sisa = String.valueOf(tblpenjualan.getValueAt(baris, 11));
            txtsisa.setText(sisa);
            String total = String.valueOf(tblpenjualan.getValueAt(baris, 12));
            txttotal.setText(total);

        }
    }//GEN-LAST:event_tblpenjualanMouseClicked

    private void txttanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttanggalActionPerformed
        // TODO add your handling code here:
        tanggalotomatis();
    }//GEN-LAST:event_txttanggalActionPerformed

    private void txtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsubtotalActionPerformed
        // TODO add your handling code here:
//      String subtotalText = txtsubtotal.getText().trim();
//      String totalText = txttotal.getText().trim();
//
//      if (!subtotalText.isEmpty() && !totalText.isEmpty()) {
//        int d = Integer.parseInt(subtotalText);
//        int e = Integer.parseInt(totalText);
//        int f = e + d;
//        txttotal.setText(String.valueOf(f));
//    } 
    }//GEN-LAST:event_txtsubtotalActionPerformed

    private void txtbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbayarActionPerformed
        // TODO add your handling code here:
//        double a;
//        double b;
//        double c;
//        a = Double.parseDouble(txtbayar.getText());
//        b = Double.parseDouble(txttotal.getText());
//        c = a - b;
//        txtsisa.setText(String.valueOf(c)); 
    }//GEN-LAST:event_txtbayarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncari;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnhitung;
    private javax.swing.JButton btnsave;
    private javax.swing.JComboBox<String> cmbkodebarang;
    private javax.swing.JComboBox<String> cmbpetugas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tblpenjualan;
    private javax.swing.JTextField txtbayar;
    private javax.swing.JTextField txtfaktur;
    private javax.swing.JTextField txthrgjual;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtnmbarang;
    private javax.swing.JTextField txtpetugas;
    private javax.swing.JTextField txtsisa;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txtsubtotal;
    private javax.swing.JTextField txttanggal;
    private javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
