
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.Connection;
import javax.swing.JOptionPane;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SMKI Utama7
 */
public class Form_Petugas extends javax.swing.JFrame {

    private DefaultTableModel model;
    /**
     * Creates new form Form_Petugas
     */
    public Form_Petugas() {
        initComponents();
        loadData();
        kosong();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidpetugas = new javax.swing.JTextField();
        txtnamapetugas = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtalamatpetugas = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtemailpetugas = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txttelponpetugas = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpetugas = new javax.swing.JTable();
        btnaddnew = new javax.swing.JButton();
        btnupdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        btncancel = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Entri Data Petugas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addContainerGap(155, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 40));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("ID Petugas");

        jLabel3.setText("Nama Petugas");

        txtidpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidpetugasActionPerformed(evt);
            }
        });

        jLabel4.setText("Alamat Petugas");

        txtalamatpetugas.setColumns(20);
        txtalamatpetugas.setRows(5);
        jScrollPane1.setViewportView(txtalamatpetugas);

        jLabel5.setText("E-Mail");

        txtemailpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailpetugasActionPerformed(evt);
            }
        });

        jLabel6.setText("Telpon");

        jLabel7.setText("Maksimal 15 Digit");

        tabelpetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelpetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelpetugasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelpetugas);

        btnaddnew.setText("Add New");
        btnaddnew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddnewActionPerformed(evt);
            }
        });

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        btncancel.setText("Cancel");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btnclose.setText("Close");
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtemailpetugas)
                            .addComponent(txtidpetugas)
                            .addComponent(txtnamapetugas)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txttelponpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnaddnew, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btndelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btncancel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnclose, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtidpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtnamapetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtemailpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttelponpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnaddnew)
                    .addComponent(btnupdate)
                    .addComponent(btndelete)
                    .addComponent(btncancel)
                    .addComponent(btnclose))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 470, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void loadData(){
        //Membuat Model
        model = new DefaultTableModel();
        
        //Menghapus Seluruh Data
        model.getDataVector().removeAllElements();
        
        //Memberi Tahu Bahwa Data Telah Kosong
        model.fireTableDataChanged();
        
        tabelpetugas.setModel(model);
        model.addColumn("ID Petugas");
        model.addColumn("Nama Petugas");
        model.addColumn("Alamat");
        model.addColumn("Email");
        model.addColumn("Telpon");
        
        try{
            
        String sql = "SELECT * FROM tblpetugas";
        
        Connection c = Koneksi.getKoneksi();
        Statement s = c.createStatement();
        ResultSet r = s.executeQuery(sql);
        
        while(r.next()){
        //Lakukan Penelusuran Baris
        model.addRow(new Object[]{
            r.getString(1),
            r.getString(2),
            r.getString(3),
            r.getString(4),
            r.getString(5)
        });
    }
    tabelpetugas.setModel(model);
    }catch(SQLException e){
        System.out.println("Terjadi Error");
    }
}
    private void kosong(){
        txtidpetugas.setText(null);
        txtnamapetugas.setText(null);
        txtalamatpetugas.setText(null);
        txtemailpetugas.setText(null);
        txttelponpetugas.setText(null);
    }
    
    private void txtidpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidpetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidpetugasActionPerformed

    private void txtemailpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailpetugasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailpetugasActionPerformed

    private void btnaddnewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddnewActionPerformed
        // TODO add your handling code here:
        String id = txtidpetugas.getText();
        String nama = txtnamapetugas.getText();
        String alamat = txtalamatpetugas.getText();
        String email = txtemailpetugas.getText();
        String telpon = txttelponpetugas.getText();
        
        
        if ("".equals(id) ||
            "".equals(nama) ||
            "".equals(alamat) ||
            "".equals(email) ||
            "".equals(telpon))
        {
            JOptionPane.showMessageDialog(this,
                    "Harap Lengkapi Data",
                    "Error", JOptionPane.WARNING_MESSAGE);  
        } else {
            
            try{
                Connection c = Koneksi.getKoneksi();
                String sql = "INSERT INTO tblpetugas VALUES (?, ?, ?, ?, ?)";
                PreparedStatement p = c.prepareStatement(sql);
                
                p.setString(1, id);
                p.setString(2, nama);
                p.setString(3, alamat);
                p.setString(4, email);
                p.setString(5, telpon);
                
                p.executeUpdate();
                p.close();
                
                JOptionPane.showMessageDialog(null,
                        "Data Berhasil diSimpan");
                
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,
                        e.getMessage());
            }finally{
                loadData();
                kosong();
            }
        }
    }//GEN-LAST:event_btnaddnewActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        // TODO add your handling code here:
        kosong();
    }//GEN-LAST:event_btncancelActionPerformed

    private void tabelpetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelpetugasMouseClicked
        // TODO add your handling code here:
        int baris = tabelpetugas.getSelectedRow();
        
        if(baris == -1){
            
            return;
        }
        
        String id = tabelpetugas.getValueAt(baris, 0).toString();
        txtidpetugas.setText(id);
        String nama = tabelpetugas.getValueAt(baris, 1).toString();
        txtnamapetugas.setText(nama);
        String alamat = tabelpetugas.getValueAt(baris, 2).toString();
        txtalamatpetugas.setText(alamat);
        String email = tabelpetugas.getValueAt(baris, 3).toString();
        txtemailpetugas.setText(email);
        String telpon = tabelpetugas.getValueAt(baris, 4).toString();
        txttelponpetugas.setText(telpon);
    }//GEN-LAST:event_tabelpetugasMouseClicked

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int i = tabelpetugas.getSelectedRow();
        
        if(i == -1){
            JOptionPane.showMessageDialog(this,
                    "Harap Pilih Data Terlebih Dahulu",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String IDPetugas = (String) model.getValueAt(i, 0);
        
        try{
            Connection c = Koneksi.getKoneksi();
            
            String sql = "DELETE FROM tblpetugas WHERE IDPetugas = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, IDPetugas);
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil diHapus");
        } catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, "Terjadi Error" + e.getMessage());
        } finally {
            loadData();
            kosong();
        }
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:
        int i = tabelpetugas.getSelectedRow();
        
        if(i == -1){
            JOptionPane.showMessageDialog(this,
                    "Harap Pilih Data Terlebih Dahulu",
                    "Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id = (String) model.getValueAt(i, 0);
        String nama = txtnamapetugas.getText();
        String alamat = txtalamatpetugas.getText();
        String email = txtemailpetugas.getText();
        String telpon = txttelponpetugas.getText();
        
        try{
            Connection c = Koneksi.getKoneksi();
            
            String sql = "UPDATE tblpetugas SET NamaPetugas = ?, Alamat = ?, Email = ?, Telpon = ? WHERE IDPetugas = ?";
                    
            PreparedStatement p = c.prepareStatement(sql);
            
            p.setString(1, nama);
            p.setString(2, alamat);
            p.setString(3, email);
            p.setString(4, telpon);
            p.setString(5, id);
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil diUbah");
        } catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, "Terjadi Error" + e.getMessage());
        } finally {
            loadData();
            kosong();
        }
    }                                       

    private void btnhapusActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int i = tabelpetugas.getSelectedRow();
        
        if(i == -1){
            JOptionPane.showMessageDialog(this,
                    "Harap Pilih Data Terlebih Dahulu",
                    "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        String id = (String) model.getValueAt(i, 0);
        
        try{
            Connection c = Koneksi.getKoneksi();
            
            String sql = "DELETE FROM tblpetugas WHERE ID = ?";
            
            PreparedStatement p = c.prepareStatement(sql);
            p.setString(1, id);
            p.executeUpdate();
            p.close();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil diHapus");
        } catch(SQLException e) {
                    JOptionPane.showMessageDialog(null, "Terjadi Error" + e.getMessage());
        } finally {
            loadData();
            kosong();
        }
    }//GEN-LAST:event_btnupdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_Petugas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form_Petugas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnaddnew;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelpetugas;
    private javax.swing.JTextArea txtalamatpetugas;
    private javax.swing.JTextField txtemailpetugas;
    private javax.swing.JTextField txtidpetugas;
    private javax.swing.JTextField txtnamapetugas;
    private javax.swing.JTextField txttelponpetugas;
    // End of variables declaration//GEN-END:variables
}
